import {LanguageProps} from '../types/LanguageTypes';

export const eng: LanguageProps = {
  id: 'eng',
  settingScreen: 'Setting',
  theme: 'Theme',
  language: 'Language',
  fontSize: 'Font size',
  dark: 'dark',
  light: 'light',
  eng: 'eng',
  kor: 'kor',
  plus: 'plus',
  division: 'division',
  subtraction: 'subtraction',
  multiply: 'multiply',
  mix: 'mix',
  custom: 'custom',
  myInfo: 'My Info',
  ranking: 'ranking',
  logout: 'Logout',
  logintError: 'fail to login',
  confirm: 'OK',
  result: 'Result',
  retry: 'Retry',
  history: 'history',
};

export const kor: LanguageProps = {
  id: 'kor',
  settingScreen: '설정',
  theme: '테마',
  language: '언어',
  fontSize: '글자 크기',
  dark: '다크',
  light: '라이트',
  eng: '영어',
  kor: '한국어',
  plus: '더하기',
  division: '나누기',
  subtraction: '빼기',
  multiply: '곱하기',
  mix: '혼합',
  custom: '커스텀',
  myInfo: '내 정보',
  ranking: '랭킹',
  logout: '로그아웃',
  logintError: '로그인에 실패했습니다',
  confirm: '확인',
  result: '결과',
  retry: '다시 시도',
  history: '기록',
};
