import {LanguageProps} from '../types/LanguageTypes';

export const eng: LanguageProps = {
  id: 'eng',

  settingScreen: 'Setting',
  infoEditScreen: '내 정보 수정',

  theme: 'Theme',
  language: 'Language',
  fontSize: 'Font size',
  dark: 'dark',
  light: 'light',
  eng: 'eng',
  kor: 'kor',
  plus: 'plus',
  division: 'division',
  subtraction: 'subtraction',
  multiply: 'multiply',
  mix: 'mix',
  custom: 'custom',
  myInfo: 'My Info',
  info: '정보',
  ranking: 'ranking',
  logout: 'Logout',
  loginError: 'fail to login',
  confirm: 'OK',
  result: 'Result',
  retry: 'Retry',
  history: 'history',
  cancel: 'cancel',
  email: 'email',
  name: 'name',
  save: 'save',
  alram: 'alram',

  serverError: 'server error please retry',
  noHistoryList: 'no History list',
  noRankingList: 'no Ranking list',
  failedEdit: '수정에 실패했습니다. 다시 시도해주세요.',
  successEdit: '수정되었습니다.',
  duplicatedEmail: '중복되는 이메일입니다.',

  isLogout: '로그아웃 시,\n기록 및 랭킹을 남길 수 없게됩니다.',
};

export const kor: LanguageProps = {
  id: 'kor',

  settingScreen: '설정',
  infoEditScreen: '내 정보 수정',

  theme: '테마',
  language: '언어',
  fontSize: '글자 크기',
  dark: '다크',
  light: '라이트',
  eng: '영어',
  kor: '한국어',
  plus: '더하기',
  division: '나누기',
  subtraction: '빼기',
  multiply: '곱하기',
  mix: '혼합',
  custom: '커스텀',
  myInfo: '내 정보',
  info: '정보',
  ranking: '랭킹',
  logout: '로그아웃',
  loginError: '로그인에 실패했습니다',
  confirm: '확인',
  result: '결과',
  retry: '다시 시도',
  history: '기록',
  cancel: '취소',
  email: 'Email',
  name: '이름',
  save: '저장',
  alram: '알람',

  serverError: '다시 시도 해주세요',
  noHistoryList: '기록이 없습니다',
  noRankingList: '랭킹 정보가 없습니다',
  failedEdit: '수정에 실패했습니다. 다시 시도해주세요.',
  successEdit: '수정되었습니다.',
  duplicatedEmail: '중복되는 이메일입니다.',

  isLogout: '기록 및 랭킹을 남길 수 없게됩니다.',
};
